### ISSUE TITLE
value is None, have error

### ISSUE THREAD

**Issue by vTNT** [reorx/rdl#1]
err message:
Traceback (most recent call last):
  File "./rdl.py", line 124, in <module>
    main()
  File "./rdl.py", line 118, in main
    dump(args.file_name, db)
  File "./rdl.py", line 66, in dump
    line = '%s\t%s\n' % (k, base64.b64encode(v))
  File "/usr/lib/python2.7/base64.py", line 53, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
TypeError: must be string or buffer, not None

so  maybe if v is None: it should continue

**Comment by reorx** [comment]
Can you please paste the key and value of the record that causes this exception? I'm wondering what kind of data type can DUMP out a None value.

**Comment by reorx** [comment]
I've made some changes in #2 , including the argument `--ignore-none-value` to ignore None value error of this case, feel free to check if it can fix your problem.

My understanding is that normally `redis.dump()` should not return None, only when the key is deleted after all the keys are fetched by `redis.keys()`, so this error should not be ignored by default, but rather to be an option if you expect it to happen reasonably.

**Comment by vTNT** [comment]
sorry  icannot find the key again

**Comment by vTNT** [comment]
the pr it can work.

but i have another question，  my redis key before dump, it  Has been set expire time, but when i load it to another redis server,  it‘s ttl is None.

**Comment by vTNT** [comment]
redis  command dump/restore cannot save expire time, so maybe i need reset expire time bymyself

**Comment by vTNT** [comment]
And when it dump data into the file,  it also can Query expiration time and Output to other files.  So maybe you can add an option。

**Comment by reorx** [comment]
That's an interest question, currently rdl does not support TTL and expiration time of the key, implementing this feature takes time and effort, I think it's better to open another issue to describe this specific requirement.
